name: Build

on: [push]

jobs:
  build-ps2exe:
    name: Build with ps2exe and upload
    runs-on: windows-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration    
    steps:
      - uses: actions/checkout@v4
      - name: Install ps2exe module
        shell: powershell
        run: |
           Set-PSRepository PSGallery -InstallationPolicy Trusted
           Install-Module -Name PS2EXE -ErrorAction Stop      
      - name: Build with ps2exe
        shell: powershell
        run: Invoke-PS2EXE wifi-reconnect.ps1 wifi-reconnect.exe -NoConsole -Verbose -noOutput
      - name: Upload build results
        uses: actions/upload-artifact@v4
        with:
          name: wifi-reconnect-build
          path: wifi-reconnect.exe
      # Commit and push all changed files.
      - name: GIT Commit Build Artifacts (exe)
        # Only run on main branch push (e.g. after pull request merge).
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push          